apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432 # default port
          env:
            - name: POSTGRES_PASSWORD # this has to be provided or container will crash
              valueFrom:
                secretKeyRef: # secrets can be obtained implicitly by anyone who can create a pod
                  name: pgpassword # using generic on the command line indicates an opaque type, which just means arbitrary user defined data
                  key: PGPASSWORD
            - name: PGUSER
              value postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: grocery
